from typing import Any

from app.models.base import now_utc


def create_menu_item_document(
    name: str,
    description: str | None,
    price: float,
    category: str,
    image_url: str | None = None,
    is_available: bool = True,
    slug: str | None = None,
    subcategory: str | None = None,
    discount_price: float | None = None,
    currency: str = "INR",
    gallery_images: list[str] | None = None,
    is_veg: bool | None = None,
    is_featured: bool = False,
    is_trending: bool = False,
    is_special: bool = False,
    rating: float = 0.0,
    rating_count: int = 0,
    preparation_time: int | None = None,
    stock_quantity: int | None = None,
    calories: int | None = None,
    tags: list[str] | None = None,
    ingredients: list[str] | None = None,
    allergens: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "name": name,
        "description": description,
        "price": price,
        "category": category,
        "slug": slug,
        "subcategory": subcategory,
        "image_url": image_url,
        "gallery_images": gallery_images or [],
        "currency": currency,
        "discount_price": discount_price,
        "is_available": is_available,
        "is_veg": is_veg,
        "is_featured": is_featured,
        "is_trending": is_trending,
        "is_special": is_special,
        "rating": rating,
        "rating_count": rating_count,
        "preparation_time": preparation_time,
        "stock_quantity": stock_quantity,
        "calories": calories,
        "tags": tags or [],
        "ingredients": ingredients or [],
        "allergens": allergens or [],
        "created_at": now_utc(),
        "updated_at": now_utc(),
    }
